### ISSUE TITLE
Design footer

### ISSUE THREAD

**Issue by mb-wali** [mb-wali/invenio-theme-tugraz#10]

**Comment by utnapischtim** [comment]
The footer should be a combination of the footer from campusonline.tugraz.at and tugraz.at, simple but there should be more information as only the impressum.

as a inspiration. there should be the part right of the tugraz.at footer: Barrierefreiheit (tip to increase better readability) + repository.tugraz.at (list: Impressum, privacy, feedback, ticket form). 

the footer should be rendered as a column system

**Comment by mb-wali** [comment]
@utnapischtim do we have an example of how it should look like? because [Campusonline](https://www.campusonline.tugraz.at/home/) & [tugraz](https://www.tugraz.at/) footers are very different.

**Comment by utnapischtim** [comment]
it should be more like the tugraz.at page

a footer with multiple columns

Repository           |     Features        |  connected services |    Accessibility
-------------------------------------------------------------------------------------------------
information              list of different       e.g.                        same as the tugraz page
about                        features               PURE
the repository                                       CampusOnline

**Comment by utnapischtim** [comment]
remove the "Information and service points" part

move impressum, datenschutzerklärung, feedback to the left column

Services: add "connected" to the title. it should indicate which tu graz systems are connected to the repository. maybe we find another word. 

"Connected Services"  set the links correct. e.g. PURE. pure.tugraz.at

"Features": the idea of features was more to show what the repository could. e.g. upload files via endpoint XY. in the beginning should only be there what invenioRDM could out of the box. then in the future it will also list all thing we add to the repository. it should not be in detail, but some nice buzzwords

and it should be more identifiable that it is a footer

**Comment by mb-wali** [comment]
> move impressum, datenschutzerklärung, feedback to the left column

First column left or just one column left?

---

>"Features": the idea of features was more to show what the repository could. e.g. 

I will put some dummy data for now. but we should find exactly what texts (buzzwords) should go there.

---

> and it should be more identifiable that it is a footer

For this, we need to change the background color, which color? or if we want to use an image as it is in [tugraz](https://www.tugraz.at) .  then which image?

**Comment by utnapischtim** [comment]
> > move impressum, datenschutzerklärung, feedback to the left column
> 
> First column left or just one column left?

first column
 
> > "Features": the idea of features was more to show what the repository could. e.g.
> 
> I will put some dummy data for now. but we should find exactly what texts (buzzwords) should go there.

perfect. we should have a conversation about that

> 
> > and it should be more identifiable that it is a footer
> 
> For this, we need to change the background color, which color? or if we want to use an image as it is in [tugraz](https://www.tugraz.at) . then which image?

make a suggestion ;)

if we use a picture, then we need a picture which has something to do with a repository, which seams difficult. therefore it should be easier to find a color. maybe the same as it is used on the tugraz.at page or we use #fafcff which is lighter and maybe with a linear-gradient direction down.
