### ISSUE TITLE
footer enhancement

### ISSUE THREAD

**Issue by mb-wali** [mb-wali/invenio-theme-tugraz#66]
- [x] Background color/image
- [x] Link to [Research Data Management](https://www.tugraz.at/sites/rdm/home/) - which column should we put this link.

These points pending for @utnapischtim feedback. 

# changes needed
- [x] Barrierefreiheit => Accessibility
- [x] remove Repository column
- [x] Accessibilityas a separate column
- [x] repository.tugraz.at => Repository

**Comment by utnapischtim** [comment]
background color/image: #fbfcff (please remove the #margin-divider above the footer)
link to Research Data Management -> Connected Services

**Comment by mb-wali** [comment]
> (please remove the #margin-divider above the footer)

Remove the whole divider div or just the ```#margin-divider``` style?

**Comment by utnapischtim** [comment]
> > (please remove the #margin-divider above the footer)
> 
> Remove the whole divider div or just the `#margin-divider` style?

the div and the style. when there is a color, then the border should not more necessary. but some margin-top should be necessary for the footer to increase the vertical space between the content and the footer.
